language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "7"
  - "8"

install:
  - npm install --only=dev

before_script:
  - ./node_modules/.bin/testrpc -u 0 -u 1 -u 2 -u 3 -u 4 -u 5 --gasLimit 100000000 --gasPrice 2000 > /dev/null &
  - sleep 5

script:
  - npm test
  - ./node_modules/.bin/truffle compile
  - ./node_modules/.bin/truffle test

notifications:
  email:
    on_success: change
    on_failure: always

